import { apiCopy } from './copy.js'

export const commandManifest = [
  { command: 'accounts', description: apiCopy.accounts.list },
  { command: 'api get', description: 'Make an authenticated raw GET request' },
  { command: 'api post', description: 'Make an authenticated raw POST request' },
  { command: 'archive', description: apiCopy.chats.archive },
  { command: 'assets download', description: apiCopy.assets.download },
  { command: 'assets upload', description: apiCopy.assets.upload },
  { command: 'auth login', description: 'Authenticate with local Beeper Desktop' },
  { command: 'auth logout', description: 'Remove local credentials' },
  { command: 'auth status', description: 'Show local auth state' },
  { command: 'chat', description: apiCopy.chats.retrieve },
  { command: 'chat open', description: 'Alias for focus' },
  { command: 'chats', description: apiCopy.chats.list },
  { command: 'chats search', description: apiCopy.chats.search },
  { command: 'clear-draft', description: 'Clear a chat draft' },
  { command: 'commands', description: 'Print the command manifest' },
  { command: 'config get', description: 'Print CLI configuration' },
  { command: 'config path', description: 'Print the config file path' },
  { command: 'config reset', description: 'Reset CLI configuration' },
  { command: 'config set', description: 'Set CLI configuration' },
  { command: 'contacts search', description: apiCopy.contacts.search },
  { command: 'create-chat', description: apiCopy.chats.create },
  { command: 'current-user', description: 'Show the OAuth userinfo response' },
  { command: 'delete-message', description: apiCopy.messages.delete },
  { command: 'doctor', description: 'Check Desktop API readiness' },
  { command: 'draft', description: 'Set a chat draft' },
  { command: 'edit', description: apiCopy.messages.update },
  { command: 'focus', description: 'Focus Beeper Desktop or one chat' },
  { command: 'llm', description: 'Print compact CLI help for agents' },
  { command: 'message', description: apiCopy.messages.retrieve },
  { command: 'mark-read', description: 'Alias for read' },
  { command: 'mark-unread', description: 'Alias for unread' },
  { command: 'messages', description: apiCopy.messages.list },
  { command: 'messages search', description: apiCopy.messages.search },
  { command: 'mute', description: 'Mute a chat' },
  { command: 'notify-anyway', description: apiCopy.chats.notifyAnyway },
  { command: 'react', description: apiCopy.reactions.add },
  { command: 'read', description: apiCopy.chats.markRead },
  { command: 'remind', description: apiCopy.reminders.create },
  { command: 'reply', description: apiCopy.messages.send },
  { command: 'reply-file', description: apiCopy.messages.send },
  { command: 'rpc', description: 'Run JSONL command RPC over stdin/stdout' },
  { command: 'search', description: 'Search chats and messages' },
  { command: 'send', description: apiCopy.messages.send },
  { command: 'send-file', description: apiCopy.messages.send },
  { command: 'shell', description: 'Run an interactive Beeper CLI shell' },
  { command: 'start-chat', description: apiCopy.chats.start },
  { command: 'status', description: 'Show Desktop API server info' },
  { command: 'tail', description: 'Alias for watch' },
  { command: 'thread', description: 'Alias for chat' },
  { command: 'threads', description: 'Alias for chats' },
  { command: 'unarchive', description: apiCopy.chats.archive },
  { command: 'unmute', description: 'Unmute a chat' },
  { command: 'unreact', description: apiCopy.reactions.delete },
  { command: 'unread', description: apiCopy.chats.markUnread },
  { command: 'unremind', description: apiCopy.reminders.delete },
  { command: 'watch', description: 'Stream Desktop API WebSocket events' },
  { command: 'whoami', description: 'Alias for current-user' },
]
