import { apiCopy } from './copy.js'

export const commandManifest = [
  { command: 'accounts', description: apiCopy.accounts.list },
  { command: 'api get', description: 'Make an authenticated raw GET request' },
  { command: 'api post', description: 'Make an authenticated raw POST request' },
  { command: 'app e2ee recovery-code mark-backed-up', description: 'Mark the recovery key as saved' },
  { command: 'app e2ee recovery-code reset begin', description: 'Create a new recovery key' },
  { command: 'app e2ee recovery-code reset confirm', description: 'Confirm a newly created recovery key' },
  { command: 'app e2ee recovery-code verify', description: 'Unlock encrypted messages with a recovery key' },
  { command: 'app e2ee verification accept', description: 'Accept a device verification request' },
  { command: 'app e2ee verification cancel', description: 'Cancel device verification' },
  { command: 'app e2ee verification qr confirm-scanned', description: 'Confirm another device scanned this QR code' },
  { command: 'app e2ee verification qr scan', description: 'Submit a scanned verification QR payload' },
  { command: 'app e2ee verification sas confirm', description: 'Confirm matching emoji verification' },
  { command: 'app e2ee verification sas start', description: 'Start emoji verification' },
  { command: 'app e2ee verification start', description: 'Start device verification' },
  { command: 'app status', description: 'Show Beeper app login and encrypted messaging state' },
  { command: 'archive', description: apiCopy.chats.archive },
  { command: 'assets download', description: apiCopy.assets.download },
  { command: 'assets upload', description: apiCopy.assets.upload },
  { command: 'auth login', description: 'Authenticate with local Beeper Desktop' },
  { command: 'auth logout', description: 'Remove local credentials' },
  { command: 'auth status', description: 'Show local auth state' },
  { command: 'avatar', description: 'Set or clear a group chat avatar' },
  { command: 'chat', description: apiCopy.chats.retrieve },
  { command: 'chat open', description: 'Alias for focus' },
  { command: 'chats', description: apiCopy.chats.list },
  { command: 'chats search', description: apiCopy.chats.search },
  { command: 'clear-draft', description: 'Clear a chat draft' },
  { command: 'commands', description: 'Print the command manifest' },
  { command: 'config get', description: 'Print CLI configuration' },
  { command: 'config path', description: 'Print the config file path' },
  { command: 'config reset', description: 'Reset CLI configuration' },
  { command: 'config set', description: 'Set CLI configuration' },
  { command: 'contacts list', description: apiCopy.contacts.list },
  { command: 'contacts search', description: apiCopy.contacts.search },
  { command: 'create-chat', description: apiCopy.chats.create },
  { command: 'current-user', description: 'Show the OAuth userinfo response' },
  { command: 'delete-message', description: apiCopy.messages.delete },
  { command: 'description', description: 'Set or clear a group chat description' },
  { command: 'doctor', description: 'Check Desktop API readiness' },
  { command: 'draft', description: 'Set a chat draft' },
  { command: 'edit', description: apiCopy.messages.update },
  { command: 'export', description: 'Export accounts, chats, messages, Markdown transcripts, and attachments' },
  { command: 'focus', description: 'Focus Beeper Desktop or one chat' },
  { command: 'interactive', description: 'Open the OpenTUI Beeper chat app' },
  { command: 'inbox', description: 'Move a chat to the primary inbox' },
  { command: 'llm', description: 'Print compact CLI help for agents' },
  { command: 'login', description: 'Authenticate with Beeper Desktop' },
  { command: 'logout', description: 'Remove local credentials' },
  { command: 'low-priority', description: 'Move a chat to Low Priority' },
  { command: 'message', description: apiCopy.messages.retrieve },
  { command: 'message-expiry', description: 'Set or clear disappearing-message expiry' },
  { command: 'mark-read', description: 'Alias for read' },
  { command: 'mark-unread', description: 'Alias for unread' },
  { command: 'messages', description: apiCopy.messages.list },
  { command: 'messages search', description: apiCopy.messages.search },
  { command: 'mute', description: 'Mute a chat' },
  { command: 'notify-anyway', description: apiCopy.chats.notifyAnyway },
  { command: 'pin', description: 'Pin a chat' },
  { command: 'react', description: apiCopy.reactions.add },
  { command: 'read', description: apiCopy.chats.markRead },
  { command: 'remind', description: apiCopy.reminders.create },
  { command: 'reply', description: apiCopy.messages.send },
  { command: 'reply-file', description: apiCopy.messages.send },
  { command: 'rpc', description: 'Run JSONL command RPC over stdin/stdout' },
  { command: 'search', description: 'Search chats and messages' },
  { command: 'send', description: apiCopy.messages.send },
  { command: 'send-file', description: apiCopy.messages.send },
  { command: 'shell', description: 'Run an interactive Beeper CLI shell' },
  { command: 'start-chat', description: apiCopy.chats.start },
  { command: 'status', description: 'Show Desktop API server info' },
  { command: 'tail', description: 'Alias for watch' },
  { command: 'thread', description: 'Alias for chat' },
  { command: 'threads', description: 'Alias for chats' },
  { command: 'title', description: 'Set a custom chat title' },
  { command: 'unarchive', description: apiCopy.chats.archive },
  { command: 'unmute', description: 'Unmute a chat' },
  { command: 'unpin', description: 'Unpin a chat' },
  { command: 'unreact', description: apiCopy.reactions.delete },
  { command: 'unread', description: apiCopy.chats.markUnread },
  { command: 'unremind', description: apiCopy.reminders.delete },
  { command: 'watch', description: 'Stream Desktop API WebSocket events' },
  { command: 'whoami', description: 'Alias for current-user' },
]
