import { apiCopy } from './copy.js'

export const commandManifest = [
  { command: 'accounts', description: apiCopy.accounts.list },
  { command: 'accounts add', description: 'Add a Beeper account' },
  { command: 'api get', description: 'Make an authenticated raw GET request' },
  { command: 'api post', description: 'Make an authenticated raw POST request' },
  { command: 'app e2ee recovery-code reset begin', description: 'Create a new recovery key' },
  { command: 'app e2ee recovery-code reset confirm', description: 'Confirm a newly created recovery key' },
  { command: 'app e2ee recovery-code verify', description: 'Unlock encrypted messages with a recovery key' },
  { command: 'app e2ee verification accept', description: 'Accept a device verification request' },
  { command: 'app e2ee verification cancel', description: 'Cancel device verification' },
  { command: 'app e2ee verification qr confirm-scanned', description: 'Confirm another device scanned this QR code' },
  { command: 'app e2ee verification qr scan', description: 'Submit a scanned verification QR payload' },
  { command: 'app e2ee verification sas confirm', description: 'Confirm matching emoji verification' },
  { command: 'app e2ee verification sas start', description: 'Start emoji verification' },
  { command: 'app e2ee verification start', description: 'Start device verification' },
  { command: 'app status', description: 'Show Beeper app login and encrypted messaging state' },
  { command: 'archive', description: apiCopy.chats.archive },
  { command: 'assets download', description: apiCopy.assets.download },
  { command: 'assets upload', description: apiCopy.assets.upload },
  { command: 'auth status', description: 'Show local auth state' },
  { command: 'avatar', description: 'Set or clear a group chat avatar' },
  { command: 'chat', description: apiCopy.chats.retrieve },
  { command: 'chats', description: apiCopy.chats.list },
  { command: 'chats search', description: apiCopy.chats.search },
  { command: 'clear-draft', description: 'Clear a chat draft' },
  { command: 'commands', description: 'Print the command manifest' },
  { command: 'config get', description: 'Print CLI configuration' },
  { command: 'config path', description: 'Print the config file path' },
  { command: 'config reset', description: 'Reset CLI configuration' },
  { command: 'config set', description: 'Set CLI configuration' },
  { command: 'contacts list', description: apiCopy.contacts.list },
  { command: 'contacts search', description: apiCopy.contacts.search },
  { command: 'create-chat', description: apiCopy.chats.create },
  { command: 'current-user', description: 'Show the OAuth userinfo response' },
  { command: 'delete-message', description: apiCopy.messages.delete },
  { command: 'description', description: 'Set or clear a group chat description' },
  { command: 'doctor', description: 'Check Desktop API readiness' },
  { command: 'draft', description: 'Set a chat draft' },
  { command: 'edit', description: apiCopy.messages.update },
  { command: 'env', description: 'Print shell setup for Beeper CLI-managed tools' },
  { command: 'env install', description: 'Add Beeper CLI-managed tools to your shell PATH' },
  { command: 'export', description: 'Export accounts, chats, messages, Markdown transcripts, and attachments' },
  { command: 'focus', description: 'Focus Beeper Desktop or one chat' },
  { command: 'inbox', description: 'Move a chat to the primary inbox' },
  { command: 'install', description: 'Install Beeper Desktop' },
  { command: 'install desktop', description: 'Install Beeper Desktop' },
  { command: 'install server', description: 'Install Beeper Server locally' },
  { command: 'llm', description: 'Print compact CLI help for agents' },
  { command: 'login', description: 'Authenticate with Beeper Desktop' },
  { command: 'logout', description: 'Remove local credentials' },
  { command: 'low-priority', description: 'Move a chat to Low Priority' },
  { command: 'message', description: apiCopy.messages.retrieve },
  { command: 'message-expiry', description: 'Set or clear disappearing-message expiry' },
  { command: 'messages', description: apiCopy.messages.list },
  { command: 'messages search', description: apiCopy.messages.search },
  { command: 'mute', description: 'Mute a chat' },
  { command: 'notify-anyway', description: apiCopy.chats.notifyAnyway },
  { command: 'pin', description: 'Pin a chat' },
  { command: 'profile disable', description: 'Disable login start for a local Beeper server profile' },
  { command: 'profile enable', description: 'Start a local Beeper server profile at login' },
  { command: 'profile list', description: 'List local Beeper profiles' },
  { command: 'profile logs', description: 'Print local Beeper profile logs' },
  { command: 'profile new', description: 'Create a local Beeper profile' },
  { command: 'profile remove', description: 'Remove a local Beeper profile' },
  { command: 'profile restart', description: 'Restart a local Beeper server profile' },
  { command: 'profile start', description: 'Start a local Beeper profile' },
  { command: 'profile status', description: 'Show local Beeper profile status' },
  { command: 'profile stop', description: 'Stop a local Beeper server profile' },
  { command: 'react', description: apiCopy.reactions.add },
  { command: 'read', description: apiCopy.chats.markRead },
  { command: 'remind', description: apiCopy.reminders.create },
  { command: 'rpc', description: 'Run JSONL command RPC over stdin/stdout' },
  { command: 'search', description: 'Search chats and messages' },
  { command: 'send file', description: 'Send a file to a chat' },
  { command: 'send text', description: apiCopy.messages.send },
  { command: 'setup', description: 'Set up a Beeper target' },
  { command: 'shell', description: 'Run an interactive Beeper CLI shell' },
  { command: 'start-chat', description: apiCopy.chats.start },
  { command: 'status', description: 'Show Desktop API server info' },
  { command: 'target list', description: 'List Beeper targets' },
  { command: 'target add', description: 'Connect to an existing Beeper client' },
  { command: 'target use', description: 'Set the default Beeper target' },
  { command: 'target info', description: 'Show Beeper target details' },
  { command: 'target remove', description: 'Remove a Beeper target' },
  { command: 'title', description: 'Set a custom chat title' },
  { command: 'unarchive', description: apiCopy.chats.archive },
  { command: 'unmute', description: 'Unmute a chat' },
  { command: 'unpin', description: 'Unpin a chat' },
  { command: 'unreact', description: apiCopy.reactions.delete },
  { command: 'unread', description: apiCopy.chats.markUnread },
  { command: 'unremind', description: apiCopy.reminders.delete },
  { command: 'update', description: 'Check and install Beeper updates' },
  { command: 'verify', description: 'Verify this Beeper target for encrypted messages' },
  { command: 'watch', description: 'Stream Desktop API WebSocket events' },
]
